# render.yaml
services:
  # Define el servicio web para tu aplicación Streamlit
  - type: web
    name: specbot # El nombre que quieras para tu app
    env: python # El entorno de ejecución
    plan: free # Usa el plan gratuito de Render
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run app.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.5 # Especifica la versión de Python que usas
      - key: OPENAI_API_KEY
        fromSecret: true # Indica que se tomará de los "Secrets" de Render
      - key: APP_PASSWORD
        fromSecret: true # También se tomará de los "Secrets"
    # --- Almacenamiento Persistente para FAISS ---
    #disks:
     # - name: faiss_storage
     #   mountPath: /app/vector_store_faiss_multimodal # ¡Muy importante!
     #  sizeGB: 1 # 1 GB es suficiente para empezar
